### DISCUSSION TITLE
Theia extension custom logo

### DISCUSSION THREAD

**Discussion by wassimkha** [eclipse-theia/theia#10223] [Q&A]
Hi,

I recently upgraded my theia from `1.14` to `1.18` and my theia extension logo broke. 

Before, to set the logo, I created my own css class:
```css
.icon-class {
  -webkit-mask: url('logo-no-text.svg');
  mask: url('logo-no-text.svg');
}
```

then I would set the `iconClass` class of that module to be equal to `"icon-class"`. 

After upgrading theia to the `1.18` version, this seems to not work anymore. Is there something new that was added recently that could have broken this?
