### DISCUSSION TITLE
When we try to install any extensions which supports browser in Theia IDE web is not working.

### DISCUSSION THREAD

**Discussion by Gopikrishna-GitHB** [eclipse-theia/theia#11998] [Q&A] [answered]
When I try to install any extensions which supports browser in Theia IDE web is not working. Attached screenshot for the reference. Here for Example installed Thunder client extension.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/85285581/207779801-65c0fa2b-79f8-4702-b1f4-7598afa94991.png)

**Comment by msujew** [comment]
Hey @Gopikrishna-GitHB,

Theia uses a special URL to fetch the content of each webview. The URL actually points to an express endpoint that the Theia backend sets up for these webviews. Each endpoint uses the form of `<guid>.webview.<original-domain>`. I assume that your `azurewebsites.net` domain doesn't forward request to these "fake domains" and so your browser can't resolve them. You'll need to configure the reverse proxy to correctly forward the request to the Theia backend.

**Reply by Gopikrishna-GitHB** [reply]
@msujew Thanks for the reply, Your comment helped to try the approach. I have further clarification that how to create reverse proxy for Linux OS app service, Also how to apply reverse proxy on the installed extensions. If you have more detailed idea on it, please provide me some inputs, so that it will be more helpful. We are stuck on this for more than 10 days. 

Thanks in advance.

**Reply by msujew** [reply]
I'm not too familiar with running Theia on a cloud platform, but maybe the guys from the [theia.cloud](https://github.com/eclipsesource/theia-cloud) project can help you. cc @jfaltermeier

**Reply by Gopikrishna-GitHB** [reply]
@msujew Thank you for your reference. 
@jfaltermeier Could you please help us on the above issue.

**Reply by jfaltermeier** [reply]
Hi, Theia Cloud helps to launch Theia based applications on Kubernetes. So I am not familiar with Azure App Services.

On Kubernetes you usually expose the running Theia Application via an Ingress. I think an ingress that also exposes the webviews would look similar to this (in the example Theia is available at my-theia.io/uuid/) by using `"*.webview.my-theia.io"` with a wildcard. 
```
spec:
  tls:
  - hosts:
    - my-theia.io
    - "*.webview.my-theia.io"
    secretName: ws-cert-secret
  rules:
  - host: my-theia.io
    http:
      paths:
      - backend:
          service:
            name: f9561aba-3149-481a-862d-9d44b09a2f17-service-591baccc-3750-46b
            port:
              number: 3000
        path: /uuid(/|$)(.*)
        pathType: Prefix
  - host: "*.webview.my-theia.io"
    http:
      paths:
      - backend:
          service:
            name: f9561aba-3149-481a-862d-9d44b09a2f17-service-591baccc-3750-46b
            port:
              number: 3000
        path: /uuid(/|$)(.*)
        pathType: Prefix
```

This basically configures the reverse proxy in the Kubernetes/Theia Cloud case (here the reverse proxy is an nginx server provided by the Kubernetes nginx ingress controller). 


So for Azure App Services I assume you had to configure your `azurewebsites.net`-domain to point to the Theia Application at a specific port. I would guess that you need to add additional config with a wildcard `*.webview` there as well. However, as mentioned, I am not familiar with Azure App Services.

**Reply by Gopikrishna-GitHB** [reply]
@jfaltermeier Thank you for your comment. 
could you please help us regarding the nginx.conf file adding to the docker container.

**Reply by Gopikrishna-GitHB** [reply]
@jfaltermeier tried the same as which you mentioned in the comment, by deploying the Theia in Azure Kubernetes Service. But Still we are facing the same issue. I am attaching the screenshot for your reference.  And also attaching the nginx ingress controller code used for reverse proxying and Wildcard.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: theia-next
  namespace: theia
spec:
  tls:
   - hosts:
   - testrev.eastus.cloudapp.azure.com
   - "*.webview.testrev.eastus.cloudapp.azure.com"
    secretName: ws-cert-secret
  ingressClassName: nginx
  rules:
  - host: "*.webview.testrev.eastus.cloudapp.azure.com"
    http:
      paths:
      - backend:
          service:
            name: theia-next
            port:
              number: 3000
        path: /uuid(/|$)(.*)
        pathType: Prefix
  - host: testrev.eastus.cloudapp.azure.com
    http:
      paths:
      - backend:
          service:
            name: theia-next
            port:
              number: 80
        path: /
        pathType: Prefix
```

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/85285581/209933855-7680eb95-4609-4b31-85fa-5e2d1d8d966d.png)

**Reply by Gopikrishna-GitHB** [reply]
@jfaltermeier @msujew Please help me on the above issue, once you are available. 
Thanks in Advance.

**Reply by jfaltermeier** [reply]
I think the paths and the port numbers should be the same for both the rules. 
In your snippet we have "80" vs "3000" and "/" vs "/uuid(/|$)(.*)"

In general:
In my example above the workspace URL would look like this:
https://my-theia.io/uuid/#/path/to/project/files

In the metadata part of the ingress I have those annotations:
```
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header 'X-Forwarded-Uri' $request_uri;
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/rewrite-target: /$2
```
    
and the path looks like this: `/uuid(/|$)(.*)`

The annotations make sure that the part of the URL after /uuid/ is rewritten. 
For "/" as a path this might not be required, however the `nginx.ingress.kubernetes.io/proxy-buffer-size: 8k` might be required

**Reply by Gopikrishna-GitHB** [reply]
@jfaltermeier Thank you for your reply.
There was some misunderstanding in the content seems, We are facing issue in the VS Code Extensions which we installed in the Theia IDE Workspace, Theia IDE workspace is loading and working fine. 

VS Code Extensions rendering URL looks like:
https://42376344-1592-46b6-9b5e-112da1247418.webview.testrev.eastus.cloudapp.azure.com/webview/index.html?id=42376344-1592-46b6-9b5e-112da1247418

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/85285581/210486277-c3898347-393a-4a01-aa57-85fc28d7f480.png)

So could you please provide an solution for this issue which we are facing. Is there any way to add wildcard for this extensions URL in the Nginx ingress controller. 

Additional Information - that if we provide the domain as localhost, in the local - the extensions are working.
Attaching the screenshot and link for your reference.
http://edb9af6a-3369-4d84-b489-58586a0340c7.webview.localhost/webview/index.html?id=edb9af6a-3369-4d84-b489-58586a0340c7

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/85285581/210497130-02fe1860-ce1a-445f-a340-bbb1cabc7ed8.png)


Please let me know if there is any further clarifications.

**Reply by Gopikrishna-GitHB** [reply]
@jfaltermeier @msujew Please help us on the above issue. If you have any idea on it, please provide me some inputs, so that it will be more helpful. We are stuck on this for more than a month.

**Reply by msujew** [reply]
@Gopikrishna-GitHB I believe you misunderstood @jfaltermeier response. Your configuration features these two backend services:

```
      - backend:
          service:
            name: theia-next
            port:
              number: 3000
        path: /uuid(/|$)(.*)
        pathType: Prefix
      - backend:
          service:
            name: theia-next
            port:
              number: 80
```

But both should point to the same port:

```
      - backend:
          service:
            name: theia-next
            port:
              number: 80
        path: /uuid(/|$)(.*)
        pathType: Prefix
      - backend:
          service:
            name: theia-next
            port:
              number: 80
```

> Additional Information - that if we provide the domain as localhost, in the local - the extensions are working.
Attaching the screenshot and link for your reference.

Yes, that is as expected. As I've mentioned before, it's a reverse proxy issue.

**Reply by Gopikrishna-GitHB** [reply]
@msujew, Thanks for your reply.
We tried the changes mentioned by @jfaltermeier but we are facing the same issue again. I am once again attaching the nginx ingress controller code and attaching the screenshot for your reference.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: theia-next
  namespace: theia
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header 'X-Forwarded-Uri' $request_uri;
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - reverse.eastus.cloudapp.azure.com
    - "*.webview.reverse.eastus.cloudapp.azure.com"
    secretName: ws-cert-secret
  rules:
  - host: reverse.eastus.cloudapp.azure.com
    http:
      paths:
      - backend:
          service:
            name: theia-next
            port:
              number: 80
        path: /uuid(/|$)(.*)
        pathType: Prefix
  - host: "*.webview.reverse.eastus.cloudapp.azure.com"
    http:
      paths:
      - backend:
          service:
            name: theia-next
            port:
              number: 80
        path: /uuid(/|$)(.*)
        pathType: Prefix
```

![Screenshot 2023-01-09](https://user-images.githubusercontent.com/85285581/211294083-8eb94575-b2a2-4206-b37c-7f636038bcd9.png)

Please check it and share your suggestions. Thanks in advance.

**Reply by jfaltermeier** [reply]
In general:
The Theia Webviews can be influenced via the `THEIA_WEBVIEW_EXTERNAL_ENDPOINT` environment variable. 
The default is `{{uuid}}.webview.{{hostname}}`
The placeholders are then replaced and we get an URL as we can see in your screenshot, e.g. abc123.webview.reverse.eastus.cloudapp.azure.com

Now you have to make sure that URL of the form *.webview.reverse.eastus.cloudapp.azure.com are available and routed to the running theia. This is the required configuration. 

Back to your concrete problem:
I can see that there is a Theia application available at the moment at https://reverse.eastus.cloudapp.azure.com/

What confuses me is that according to the ingress yaml you have pasted the URL of theia should be https://reverse.eastus.cloudapp.azure.com/uuid/ (because of the path segment). This results in a 404 however. 

Are you sure that your kubernetes ingress is actually used to serve this Theia application?

Different things you may try for debugging the issue:
* You may try to set `THEIA_WEBVIEW_EXTERNAL_ENDPOINT` to something without the `{{uuid}}` wildcard. This way you should be able to avoid wildcard in the proxy configuration for now. Once you got it working without the uuid, it may be easier to adapt the configuration accordingly (Should be done because of security reasons: https://github.com/eclipse-theia/theia/blob/e292e0efff25da6a81c86acc828b97d9d02bba8a/doc/changelogs/CHANGELOG-2019.md)
* Check the logs of Theia and the ingress controller for any hints
* Check the Kubernetes related documentation: https://kubernetes.io/docs/concepts/services-networking/ingress/ and https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/

**Reply by Gopikrishna-GitHB** [reply]
@jfaltermeier Thanks for your reply. 

_Are you sure that your kubernetes ingress is actually used to serve this Theia application?_

As you mentioned, when we add the /uuid(/|$)(.*) in the path Theia Application is not working. If we replace the /uuid(/|$)(.*) with / only it works. so we are using the configuration as below:

- host: reverse.eastus.cloudapp.azure.com
    http:
      paths:
      - backend:
          service:
            name: theia-next
            port:
              number: 80
        path: /
        pathType: Prefix

**Reply by jfaltermeier** [reply]
Ok, and for the webview related entry you are using / as well?

```
  - host: "*.webview.reverse.eastus.cloudapp.azure.com"
    http:
      paths:
      - backend:
          service:
            name: theia-next
            port:
              number: 80
        path: /
        pathType: Prefix
```
