### DISCUSSION TITLE
Theia Extension Running in a pod

### DISCUSSION THREAD

**Discussion by BarryDrez** [eclipse-theia/theia#12594] [Q&A]
Can someone please point me to a good set of instructions for configuring Kubernetes so that I can run my Theia extension in a pod? There is something wrong with my environment.  I am unable to edit any files in my workspace. Do I need an ephemeral volume for my workspace?  When I run my extension outside of k8s, everything works correctly.
Thank you

**Comment by msujew** [comment]
cc @jfaltermeier since you had done a bit of work in that area with theia.cloud, do you have any idea what could be wrong here?

**Reply by jfaltermeier** [reply]
@BarryDrez I think you might have to configure a `securityContext` for your pod: 
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods

`runAsUser`, `runAsGroup`, and `fsGroup` should match the unix user identifier of the user used in the docker image. 
The easiest way to find this, if not known, would be to run your docker image locally, and run `id` on the Theia terminal:

```
$ id
uid=101(theia) gid=101(theia) groups=101(theia)
# -> id is 101
``` 

(Please note that if you are testing with minikube, you have to use the mount command with `uid` and `gid` to get a volume with the expected permissions: https://minikube.sigs.k8s.io/docs/commands/mount/ )

**Reply by BarryDrez** [reply]
Thank you @jfaltermeier.  I will try this and let you know.

**Reply by BarryDrez** [reply]
Hi @jfaltermeier When I run id, I get the following:
uid=1724(sagadmin) gid=1724(sagadmin) groups=1724(sagadmin)
sagadmin is our user id.

**Reply by BarryDrez** [reply]
@jfaltermeier Can you point me to how the volume for theia cloud is configured?

**Reply by jfaltermeier** [reply]
```
spec:
  #...
    spec:
      volumes:
        #...
        - name: user-data
          persistentVolumeClaim:
            claimName: a616e867-6796-42cd-a9b4-365f01807c96-pvc-ws-asdfghjkl-theia-cl
      initContainers:
        #...
      containers:
        - name: oauth2-proxy
          #...
        - name: theia-cloud-demo
          image: theiacloud/theia-cloud-demo:0.8.0.MS10
          #...
          env:
            #...
          resources:
            #...
          volumeMounts:
            - name: user-data
              mountPath: /home/project/persisted
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 101
            runAsGroup: 101
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 101
```
This is from a `Deployment` created with Theia Cloud where the user id was 101. 
The volume is a `persistentVolumeClaim` that was created upfront. It is mounted at `/home/project/persisted` in the Theia container. 
The securityContext is set up for a user with id 101. So in your case this would be 1724 then.
