### DISCUSSION TITLE
Readiness probe for theia

### DISCUSSION THREAD

**Discussion by habibali95** [eclipse-theia/theia#8790] [Q&A]
Any idea what's the best readiness probe configuration for theia ?

this is my current configuration 
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5

but sometimes after the readiness probe is finished with success, theia returns 503..

**Comment by habibali95** [comment]
app prober config does not exists for /app-health/theia/readyz 

when i invoke curl -HI -X -v localhost:15020/app-health/theia/readyz from inside the pod

**Comment by azatsarynnyy** [comment]
You can try HTTP probe instead of TCP probe, e.g.:
```yaml
readinessProbe:
          httpGet:
            port: 3000
            scheme: HTTP
```
or try to experiment with `successThreshold` parameter
