### ISSUE TITLE
Theia File Icons Theme - Quick Pick Styling

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#10089]
### Bug Description:
Since #9864

In the `Open recent workspace...` file picker, the icons are partially cut off to the left of the text.
 
![image](https://user-images.githubusercontent.com/62660806/133108511-539b4d4d-c6ed-4bef-9781-7cd83648b1dc.png)

### Steps to Reproduce:

1. You must have some entries in your workspace history file. (Open some workspaces if you haven't or if you're using a temporary THEIA_CONFIG_DIR )
2. Set your icon theme to File Icons (Theia)
2. Use the open recent workspace command (File > Open recent workspace...)
3. Observe that the icons are cut off

### Additional Information

- Operating System: RHEL7
- Theia Version: `master`

**Comment by colin-grant-work** [comment]
@msujew, if you're interested.

**Comment by msujew** [comment]
Sure, I'll take a look at that tomorrow 👍

**Comment by vince-fugnitto** [comment]
Another annoying thing is having the separators for each entry (which is needed to add the last modified date).

**Comment by Alnyli07** [comment]
It seems to be broken again. 

<img width="633" alt="Screen Shot 2022-04-27 at 16 03 54" src="https://user-images.githubusercontent.com/9317724/165524253-7b7f2482-a4a5-4a17-853a-4b28ad858628.png">

Following css code block brokes alignment:

```css 
/*@theia/filesystem/src/browser/style/file-icons.css*/
.theia-file-icons-js {
    /*
    Here, the `line-height` ensures that FontAwesome and `file-icons-js` container has the same height.
    Ideally, it would be 1 em, but since we set the max height above (and other places too) with 0.8
    multiplier, we use 0.8 em here too.
     */
    line-height: 0.8em;
}
```

**version**: 1.24.0
