### ISSUE TITLE
core: regression when using `iconClass`

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#10231]
### Discussed in https://github.com/eclipse-theia/theia/discussions/10223

<div type='discussions-op-text'>

<sup>Originally posted by **wassimkha** October  5, 2021</sup>
Hi,

I recently upgraded my theia from `1.14` to `1.18` and my theia extension logo broke. 

Before, to set the logo, I created my own css class:
```css
.icon-class {
  -webkit-mask: url('logo-no-text.svg');
  mask: url('logo-no-text.svg');
}
```

then I would set the `iconClass` class of that module to be equal to `"icon-class"`. 

After upgrading theia to the `1.18` version, this seems to not work anymore. Is there something new that was added recently that could have broken this?
</div>
