### ISSUE TITLE
regression: socket.io breaks reverse-proxy + non-root URL

### ISSUE THREAD

**Issue by parsley42** [eclipse-theia/theia#10853]
### Bug Description:
Prior to the socket.io merge, I was running Theia in containers in a Kubernetes cluster on a random sub-path using an ingress definition like this:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/random-string)$ $1/ redirect;
  name: my-theia
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: my-theia.example.com
      http:
        paths:
          - backend:
              service:
                name: my-theia
                port:
                  number: 80
            path: /random-string(/|$)(.*)
            pathType: Prefix
  tls:
    - hosts:
        - my-theia.example.com
```
... this allowed me to connect to a theia node server at https://my-theia.example.com/random-string

Now when I try to connect, I get a spinning wheel, and in the network console I see the browser code is trying to connect to the absolute path '/socket.io/?EIO=4&transport=polling&t=XXXXXX', which breaks the app.

### Steps to Reproduce:

1. Run a simple theia service behind a reverse proxy with a non-root path and rewrite rule for the path
2. Connect to the service and observe the browser tools network tab
3. Note that almost all request paths don't have a leading / - but the /socket.io request does
4. ... theia doesn't work

### Additional Information

- Operating System:
- Theia Version:
