### ISSUE TITLE
Can't build from latest repo version

### ISSUE THREAD

**Issue by MacGyver27** [eclipse-theia/theia#11244]
### Additional Information

- Operating System: debian 11/docker
- Theia Version: latest

```
version: "3.7"

services:
  theia:
    container_name: general.theia.50114
    build: theia-full-docker
    restart: always
    user: root
    ports:
      - 50114:3000
    volumes:
      - $PWD/projects:/home/project:cached
      - /docker/fitness:/home/project/fitness:rw
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - GO_VERSION=1.16

networks:
  default:
    name: general.theia
```

```
Building native extensions. This could take a while...
Successfully installed jaro_winkler-1.5.4
Successfully installed rexml-3.2.5
Successfully installed kramdown-2.4.0
Successfully installed kramdown-parser-gfm-1.1.0
Successfully installed ast-2.4.2
Successfully installed parser-3.1.2.0
Building native extensions. This could take a while...
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.6-x64-unknown.gemspec.rz)
Successfully installed racc-1.6.0
ERROR: Service 'theia' failed to build : The command '/bin/sh -c apt-get update && apt-get -y install ruby ruby-dev zlib1g-dev &&     gem install solargraph' returned a non-zero code: 1
```
