### ISSUE TITLE
theming: `tab.activeBorderTop` is not applied properly

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#11616]
#### Bug Description:

The theming option `tab.activeBorderTop` is not applied properly (notice the missing green border).

_theia_:

![Screen Shot 2022-08-26 at 12 48 52 PM](https://user-images.githubusercontent.com/40359487/186954354-2fbfc14d-f389-4707-9fd5-e1c0d059100a.png)

_vscode_:

![Screen Shot 2022-08-26 at 12 50 14 PM](https://user-images.githubusercontent.com/40359487/186954402-dd737128-cfc4-4562-bbdf-83951b41f814.png)

#### Steps to Reproduce:

1. include the following test theme ([active-border](https://github.com/eclipse-theia/theia/files/9434936/active-border-0.0.1.vsix.zip))
2. start the application
3. trigger the command `Preferences: Color Theme` and select `Active Border`
4. open a tab and notice that the border is not applied properly

**Comment by vince-fugnitto** [comment]
The styling does exist but does not seem to work (`box-shadow` with `inset`):

```css
theia-main-content-panel .p-TabBar .p-TabBar-tab.p-mod-current {
    color: var(--theia-tab-activeForeground);
    background: #1e1e1e;
    box-shadow: 0 1px 0 #a2ff00, 0 -1px 0 transparent inset;
}
```
