### ISSUE TITLE
Toast styling broken in some themes

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#11710]
### Bug Description:

In some themes, toasts become transparent on hover.

### Steps to Reproduce:

1. Set theme to `Solarized Light`
2. Get a toast (e.g. add an extension to `extensions.json` and restart)
3. Hover over the toast.
4. Observe that the toast becomes transparent, with content behind the toast showing through.

### Additional Information

![image](https://user-images.githubusercontent.com/62660806/192882457-c622aab6-9afc-4135-86d8-cf9c58b65082.png)

Here, we add the style:

https://github.com/eclipse-theia/theia/blob/22a5f7e98ec23c664bfa9916a0d7f81e727fa26a/packages/messages/src/browser/notifications-contribution.ts#L183-L190

The color in Solarized Light is `"list.hoverBackground": "#DFCA8844",`, which is somewhat transparent. What's missing is a parent component that has an opaque background. In VSCode, we have the following DOM tree:

![image](https://user-images.githubusercontent.com/62660806/192883036-104ff86a-80f2-4ed4-8f9f-e4b2d736259a.png)

and the following effective CSS:

```css
/* This is list.background and is not transparent */
.monaco-list.list_id_6 .monaco-list-rows {
	background: #eee8d5;
}

/* This is notifications.background and mostly transparent */
.monaco-list.list_id_6:not(.drop-target) .monaco-list-row:hover:not(.selected):not(.focused) {
	background-color: rgba(223, 202, 136, 0.27);
}
```

And since the parent is not transparent, we don't (seem) to see through the child.

- Theia Version: 80839c5a760c1de7221a7a870c2a63b85a46a1f6
