### ISSUE TITLE
Custom icons are not displayed in plugin view

### ISSUE THREAD

**Issue by bvenreply** [eclipse-theia/theia#13096]
### Bug Description:

Custom icons are not displayed in plugin views. It seems that (some?) custom icons are displayed as `inline` elements by default, thus ignoring the `width` property.

![image](https://github.com/eclipse-theia/theia/assets/105274814/61608f4c-86e4-428e-933e-4fbde6fc200e)

### Steps to Reproduce:

The most mainstream vscode extension I could reproduce the issue with was [ms-kubernetes-tools](https://open-vsx.org/extension/ms-kubernetes-tools/vscode-kubernetes-tools). If you have no Kubernetes clusters, you can have one displayed using this dummy kubeconfig:
```yaml
apiVersion: v1
kind: Config
current-context: dev
preferences: {}
clusters:
  - cluster:
      server: https://fake-k8s.com.local
    name: dev
users:
  - name: dev
    user:
      token: dummy
contexts:
  - name: dev
    context:
      cluster: dev
      user: dev
```
Just save it somewhere, then add it with the command *Kubernetes: Set Kubeconfig*.

Then just open the Kubernetes plugin view and note the missing icon to the left of the cluster name, as compared to vscode.

### Additional Information

- Theia Version: `1.43.1`
- Browser: Chromium version `119.0.6045.159`

I believe the issue was introduced with [this change](https://github.com/eclipse-theia/theia/pull/12827/files#diff-1d4f8a4206f04c217432c91be8bf49d10df51618f61d0f53279403b29dae27b9L113-R114), in this PR: eclipse-theia/theia/pull/12827 . I tested setting the display mode explicitly to something other than `inline`, the icons were displayed correctly in that case (see image above).
