### ISSUE TITLE
Theia browser crashing on EKS after terminal is opened.

### ISSUE THREAD

**Issue by czezi** [eclipse-theia/theia#13725]
### Bug Description:
The theia blueprint deployed on eks is crashing as soon as a new terminal is opened, nothing in the logs, cpu is spiking to max and app is crashing. Tried both arm64 and amd64 arch.

<img width="1512" alt="Screenshot 2024-05-23 at 2 04 34 AM" src="https://github.com/eclipse-theia/theia/assets/166790951/6ad54cd0-8c61-4869-bb8c-8cdc7d94a5d3">
<img width="358" alt="Screenshot 2024-05-23 at 2 04 24 AM" src="https://github.com/eclipse-theia/theia/assets/166790951/1d8a7d85-e7b0-4c63-857f-8aed9d9c4510">

### Steps to Reproduce:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
  labels:
    app: efs-app
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
    - name: app
      imagePullPolicy: Always
      image: ghcr.io/eclipse-theia/theia-blueprint/theia-ide:1.49.100
      resources:
        requests:
          memory: "1024Mi"
          cpu: "1"
        limits:
          memory: "1024Mi"
          cpu: "1"
```

### Additional Information

- Operating System: official docker image `ghcr.io/eclipse-theia/theia-blueprint/theia-ide:1.49.100`
- Theia Version: 1.49.100
