### ISSUE TITLE
latest-linux.yml was not updated for version 1.52.0

### ISSUE THREAD

**Issue by Mailaender** [eclipse-theia/theia#14069]
https://download.eclipse.org/theia/ide/1.52.0/linux/latest-linux.yml contains
```yml
version: 1.51.0
```
and the checksums do not match.

**Comment by JonasHelming** [comment]
@jfaltermeier @sgraband

**Comment by jfaltermeier** [comment]
For me the contents of the linked file looks like this:

```
version: 1.52.0
files:
  - url: TheiaIDE.AppImage
    sha512: 3tuJc0JPyyl8S7Na18vCmjlmSn1vTncl6mVrJG5iDo010DyFBfBCWbCQ4YgF/Z7xfwFnrqdAHM+95VXRtmSRxA==
    size: 206339576
    blockMapSize: 216588
  - url: TheiaIDE.deb
    sha512: Wpc5wiicJBvQCR5iMI8pPTewL9FatfXzAMSOum2DVcIJr9FSIBPTAxOLEJeYJ7ZUdW7WE/r1dzqq8Vzte14Vng==
    size: 136940716
path: TheiaIDE.AppImage
sha512: 3tuJc0JPyyl8S7Na18vCmjlmSn1vTncl6mVrJG5iDo010DyFBfBCWbCQ4YgF/Z7xfwFnrqdAHM+95VXRtmSRxA==
releaseDate: '2024-07-29T09:21:31.284Z'
```

Also the checksums look good:
```
$ openssl dgst -sha512 -binary ~/Downloads/TheiaIDE.AppImage | base64
openssl dgst -sha512 -binary ~/Downloads/TheiaIDE.deb | base64
3tuJc0JPyyl8S7Na18vCmjlmSn1vTncl6mVrJG5iDo010DyFBfBCWbCQ4YgF/Z7xfwFnrqdAHM+9
5VXRtmSRxA==
Wpc5wiicJBvQCR5iMI8pPTewL9FatfXzAMSOum2DVcIJr9FSIBPTAxOLEJeYJ7ZUdW7WE/r1dzqq
8Vzte14Vng==

```

In general the linux updater checks this location https://download.eclipse.org/theia/ide/latest/linux/latest-linux.yml
The https://download.eclipse.org/theia/ide/1.XX.0 locations are mainly used as an archive for the installers itself. The latest yaml files may be outdated there, if they are not used by any updater.
