### ISSUE TITLE
search boxes in "search in workspace" resize to imaginary tooltip ignoring white-space: nowrap;

### ISSUE THREAD

**Issue by Alexander-Taran** [eclipse-theia/theia#15229]
### Steps to Reproduce:

1. resize left panel to something small
2. focus one of search boxes in siw
3. observe textarea grow in height

### Additional Information
![Image](https://github.com/user-attachments/assets/73f457b9-2db8-46f6-865f-b3f191fab554)

![Image](https://github.com/user-attachments/assets/4a9e0424-8cc1-451e-90a4-b1e20cbcdd95)

```css
.theia-input::placeholder {
    color: var(--theia-input-placeholderForeground);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```

Looks like react-textarea-autosize calculates height based on `content || placeholder`

Disabling nowrap in style makes visible sense. But still not what one would want to see.
