### ISSUE TITLE
[theming] file-icon incorrectly displays name icon with a dot in name

### ISSUE THREAD

**Issue by kesslerdev** [eclipse-theia/theia#7680]
### Bug Description:
The file-icon is incorrectly displayed for files with a dot in name.
For instance, the icon for the following file package.json is not properly displayed (with: https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)

_Theia_
![Sélection_035](https://user-images.githubusercontent.com/2135565/80460089-9f77fe00-8933-11ea-86ea-acec9ba6a0cb.png)

_VS Code_
![Sélection_034](https://user-images.githubusercontent.com/2135565/80460108-a7d03900-8933-11ea-9eba-1238dfa88b5a.png)

### Resolution
_Theia_
![Sélection_036](https://user-images.githubusercontent.com/2135565/80460144-b4ed2800-8933-11ea-8bac-cf0c252d4b21.png)

when a class contain a dot in name, in html element don't need to escape dot but in css style definition yes!

```css
.theia-plugin-package\.json-file-name-icon.theia-plugin-json-ext-file-icon.theia-plugin-ext-file-icon.theia-plugin-file-icon, .theia-plugin-package\.json-file-name-icon.theia-plugin-json-ext-file-icon.theia-plugin-ext-file-icon.theia-plugin-file-icon::before, .theia-plugin-package-lock\.json-file-name-icon.theia-plugin-json-ext-file-icon.theia-plugin-ext-file-icon.theia-plugin-file-icon, .theia-plugin-package-lock\.json-file-name-icon.theia-plugin-json-ext-file-icon.theia-plugin-ext-file-icon.theia-plugin-file-icon::before, .theia-plugin-\.nvmrc-file-name-icon.theia-plugin-nvmrc-ext-file-icon.theia-plugin-ext-file-icon.theia-plugin-file-icon, .theia-plugin-\.nvmrc-file-name-icon.theia-plugin-nvmrc-ext-file-icon.theia-plugin-ext-file-icon.theia-plugin-file-icon::before, .theia-plugin-\.esmrc-file-name-icon.theia-plugin-esmrc-ext-file-icon.theia-plugin-ext-file-icon.theia-plugin-file-icon, .theia-plugin-\.esmrc-file-name-icon.theia-plugin-esmrc-ext-file-icon.theia-plugin-ext-file-icon.theia-plugin-file-icon::before {
    content: ' ';
    background-image: url('http://127.0.0.1:3000/hostedPlugin/PKief_material_icon_theme/icons/nodejs.svg');
    background-size: 16px;
    background-position: left center;
    background-repeat: no-repeat;
}
```
### Additional Information

- Operating System: Linux / docker
- Theia Version: next
