### ISSUE TITLE
[Bug] widget background is transparent making brand logo visible

### ISSUE THREAD

**Issue by GNSubrahmanyam** [eclipse-theia/theia#8444]
### Bug Description:
widget background is transparent. Brand logo is visble

I added a branding extension similar to https://github.com/vince-fugnitto/theia-cpp-branding.

It works fine to the extent the logo is added to the empty panel.

But when I open the preview of a markdown file, the rendered output panel has a transparent background causing the logo to be visible and conflict with the rendered preview.

### Steps to Reproduce:

1. Add brand logo 
```css
#theia-main-content-panel {
    background-image: var(--theia-brand-logo);
    background-position: center center;
    background-repeat: no-repeat;
    background-size: var(--theia-brand-logo-size);
}
```

2. Go to preferences or view any preview 
3. Brand logo is visible

![image](https://user-images.githubusercontent.com/18217008/91659551-04b04b80-eaee-11ea-84d6-fe67021874be.png)
![image](https://user-images.githubusercontent.com/18217008/91659633-9fa92580-eaee-11ea-9ff9-ac4896c0fd14.png)

### Additional Information

- Operating System:
- Theia Version: 1.5.0

cc: @vince-fugnitto
