### ISSUE TITLE
Latest Java test runner extension fails in displaying tree icons

### ISSUE THREAD

**Issue by sunix** [eclipse-theia/theia#8981]
### Bug Description:
Hello, I tried the latest Java test runner extension and there is a regression in Theia in the tree:
- The `green` passed icon is not displayed
- The `red` failed icon is not red

Maybe caused by https://github.com/microsoft/vscode-java-test/pull/1099
Related to https://github.com/eclipse-theia/theia/pull/8267

CAN NOT reproduce with [Java test runner 0.24.2](https://open-vsx.org/api/vscjava/vscode-java-test/0.24.2/file/vscjava.vscode-java-test-0.24.2.vsix)
CAN reproduce with [Java test runner 0.27.0](https://open-vsx.org/api/vscjava/vscode-java-test/0.27.0/file/vscjava.vscode-java-test-0.27.0.vsix)

### Steps to Reproduce:
With Che:

1. Start any Java workspace from Che.
2. Edit the devfile and add the custom registry url for the quarkus or java plugin for instance:
    ```yaml
     - id: redhat/quarkus-java11/latest
       type: chePlugin
       registryUrl: 'https://sunix-che-plugin-registry-java-test-runner-0-27-0.surge.sh/v3'
    ```
3. Start the workspace and run the test

With Gitpod:
1. Start the petclinic sample
2. install the Java test runner extension
3. Run the test

![Selection_170](https://user-images.githubusercontent.com/650571/105496892-6308e100-5cbe-11eb-85cf-6b88df27df48.png)

Same one in vscode:
![Selection_171](https://user-images.githubusercontent.com/650571/105497162-c98dff00-5cbe-11eb-9333-02c7258f212f.png)
